#!/usr/bin/env python3
"""
Author: Josbua Ampofo Yentumi

Problem 1: Tests for count_lines
"""


# Generated by CodiumAI

import pytest
import os
from lines import count_lines


def test_no_comments_or_blank_spaces():
    """Test correct number of lines in a file with no comments or blank spaces is returned"""
    filename = "test_file.txt"
    lines = [
        "This is line 1\n",
        "This is line 2\n",
        "# This is a comment\n",
        "\n",
        "This is line 3\n",
    ]

    with open(filename, "w") as file:
        file.writelines(lines)

    assert (count_lines(filename)) == 3
    os.remove(filename)


def test_file_not_exist():
    """Test file does not exist"""
    filename = "nonexistent_file.txt"
    assert (count_lines(filename)) == "File does not exist"


def test_empty_file_or_comments_and_blank_spaces():
    """Test count when the file is empty or only contains comments and blank spaces"""
    filename = "test_file.txt"
    lines = ["# This is a comment\n", "\n", "# Another comment\n"]

    with open(filename, "w") as file:
        file.writelines(lines)

    assert (count_lines(filename)) == 0
    os.remove(filename)


def test_single_line_file():
    """Test count with a single line"""
    filename = "test_file.txt"
    line = "This is a single line"

    with open(filename, "w") as file:
        file.write(line)

    assert (count_lines(filename)) == 1
    os.remove(filename)
